// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppLaunchTrigger = { enabled: boolean, 
/**
 * Executable file name, matched case-insensitively ("EXCEL.EXE").
 */
exe: string, 
/**
 * Wait after the app starts, so its window is ready.
 */
delay_ms: number, };
