// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CheckOutcome = { "type": "matched" } | { "type": "found", x: number, y: number, score: number, } | { "type": "timed_out" } | { "type": "interrupted" };
