// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckOutcome } from "./CheckOutcome";

/**
 * What one pixel check or Find image step did.
 */
export type CheckResult = { 
/**
 * The 1-based step number.
 */
step: number, 
/**
 * The 0-based loop it happened in.
 */
loop_idx: number, 
/**
 * A Find image step, rather than a pixel check.
 */
image: boolean, 
/**
 * How long it waited (pauses not counted).
 */
after_ms: number, outcome: CheckOutcome, };
