// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the UI shows of a macro's data file.
 */
export type DataFileInfo = { path: string, columns: Array<string>, rows: number, 
/**
 * Why the file can't be used (missing, unreadable, invalid).
 */
error: string | null, };
