// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rgb } from "./Rgb";

export type EditOp = { "op": "rename", name: string, } | { "op": "delete_step", index: number, } | { "op": "insert_wait", at: number, dur: number, label: string, } | { "op": "insert_pixel_wait", at: number, dur: number, x: number, y: number, color: Rgb, tolerance: number, timeout_ms: number, label: string, } | { "op": "set_wait_duration", index: number, dur: number, } | { "op": "update_pixel_wait", index: number, x: number, y: number, color: Rgb, tolerance: number, timeout_ms: number, } | { "op": "set_label", index: number, label: string, } | { "op": "set_pause", index: number, dur: number, } | { "op": "cap_pauses", max: number, };
