// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FinishReason = "completed" | "stopped" | "key_pressed" | "killed" | "pixel_timeout" | "error";
