// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The best match for an image on screen, with its score in percent.
 */
export type FoundImage = { x: number, y: number, w: number, h: number, score: number, };
