// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A PNG image (as [`crate::image::prepare`] makes it), serialized as base64.
 */
export type ImagePng = string;
