// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImagePng } from "./ImagePng";
import type { Rect } from "./Rect";

export type ImageTrigger = { enabled: boolean, 
/**
 * What to look for; none until one is set.
 */
image: ImagePng | null, 
/**
 * The lowest match accepted, in percent.
 */
threshold: number, 
/**
 * Where to look; everywhere if `None`.
 */
area: Rect | null, };
