// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportResult = { imported: Array<string>, 
/**
 * Files that couldn't be imported, with the reason.
 */
problems: Array<string>, };
