// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * When the widget floats above other windows.
 */
export type KeepOnTop = "always" | "sessions" | "never";
