// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KeyStroke = { code: string, 
/**
 * Windows virtual-key code; 0 when unknown (replay falls back to `code`/`ch`).
 */
vk?: number, 
/**
 * Hardware scan code; 0 when unknown.
 */
scan?: number, 
/**
 * Extended-key flag (right Ctrl/Alt, arrows, Insert/Delete, …).
 */
ext?: boolean, };
