// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A row of the Library tab.
 */
export type MacroListItem = { id: string, name: string, duration: number, step_count: number, runs: number, last_run: string | null, hotkey: string | null, };
