// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppLaunchTrigger } from "./AppLaunchTrigger";
import type { HotkeyTrigger } from "./HotkeyTrigger";
import type { PixelTrigger } from "./PixelTrigger";
import type { ScheduleTrigger } from "./ScheduleTrigger";

/**
 * All of a macro's triggers. Machine-local: kept in library.json, not in the `.rly`.
 */
export type MacroTriggers = { hotkey: HotkeyTrigger, schedule: ScheduleTrigger, app_launch: AppLaunchTrigger, pixel: PixelTrigger, };
