// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MovePoint } from "./MovePoint";
import type { PlaybackOptions } from "./PlaybackOptions";
import type { RecordingMeta } from "./RecordingMeta";
import type { Step } from "./Step";

export type MacroView = { id: string, name: string, modified_at: string, recording: RecordingMeta, playback: PlaybackOptions, steps: Array<Step>, 
/**
 * Cursor positions over time (moves and presses), for the preview path.
 */
moves: Array<MovePoint>, duration: number, };
