// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rect } from "./Rect";

export type MonitorInfo = { name: string, rect: Rect, work: Rect, dpi: number, primary: boolean, };
