// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The editor's dividers, in CSS px: the preview's width, and the heights of
 * the button row and the timeline (`None`: the default). The UI keeps them
 * inside the window.
 */
export type Panes = { preview_w: number | null, transport_h: number | null, timeline_h: number | null, };
