// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The editor's dividers, in CSS px: the preview's width and the timeline's
 * height (`None`: the default). The UI keeps them inside the window.
 */
export type Panes = { preview_w: number | null, timeline_h: number | null, };
