// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoordMode } from "./CoordMode";
import type { Repeat } from "./Repeat";

export type PlaybackOptions = { speed: number, repeat: Repeat, humanize: boolean, jitter_ms: number, stop_on_key: boolean, coord_mode: CoordMode, };
