// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MonitorInfo } from "./MonitorInfo";
import type { Rect } from "./Rect";
import type { WindowInfo } from "./WindowInfo";

export type RecordingMeta = { os: string, virtual_desktop: Rect, monitors: Array<MonitorInfo>, 
/**
 * System double-click time and distance when recorded.
 */
double_click_ms: number, double_click_px: number, anchor_window?: WindowInfo | null, };
