// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckResult } from "./CheckResult";
import type { RunOutcome } from "./RunOutcome";
import type { RunSource } from "./RunSource";

export type RunEntry = { 
/**
 * When the run started, or when the skipped trigger fired.
 */
at: string, macro_id: string, 
/**
 * The name when it ran (the macro may be renamed or deleted since).
 */
macro_name: string, source: RunSource, outcome: RunOutcome, 
/**
 * Wall time from start to end, pauses included; 0 for a skip.
 */
duration_ms: number, 
/**
 * Where on the timeline playback started.
 */
from_ms: number, 
/**
 * Loops played, the last one included even if it didn't finish.
 */
loops: number, speed: number, humanize: boolean, 
/**
 * The latest pixel checks and Find image steps, oldest first.
 */
checks: Array<CheckResult>, 
/**
 * Earlier checks that weren't kept.
 */
checks_dropped: number, 
/**
 * Why it was skipped, when the reason needs saying (a data file's problem).
 */
note?: string, };
