// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FinishReason } from "./FinishReason";
import type { SkipReason } from "./SkipReason";

export type RunOutcome = { "type": "finished", "reason": FinishReason } | { "type": "skipped", "reason": SkipReason };
