// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WeeklySchedule } from "./WeeklySchedule";

export type ScheduleTrigger = { enabled: boolean, schedule: WeeklySchedule, };
