// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PathMode } from "./PathMode";

export type Settings = { capture_moves: boolean, capture_keys: boolean, 
/**
 * 3-second countdown before recording.
 */
countdown: boolean, 
/**
 * Ignore input injected by other programs (remote-desktop tools inject
 * real user input, so their users may want this off).
 */
ignore_injected: boolean, path_mode: PathMode, show_click_labels: boolean, 
/**
 * The close button (and Alt+F4) hides Relay to the tray instead of quitting.
 */
close_to_tray: boolean, };
