// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a trigger that fired didn't run its macro.
 */
export type SkipReason = "busy" | "locked" | "missed" | "data_file";
