// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How late events were injected relative to their deadlines.
 */
export type TimingStats = { events: number, p50_ms: number, p99_ms: number, max_ms: number, };
