// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MacroTriggers } from "./MacroTriggers";

export type TriggerStatus = { triggers: MacroTriggers, 
/**
 * RFC 3339, local time.
 */
next_run: string | null, 
/**
 * Why the hotkey isn't working (taken by another app, …).
 */
hotkey_error: string | null, paused: boolean, };
