// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WeeklySchedule = { 
/**
 * Monday first.
 */
days: [boolean, boolean, boolean, boolean, boolean, boolean, boolean], 
/**
 * Local wall-clock time, serialized as "HH:MM".
 */
time: string, };
