// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rect } from "./Rect";

/**
 * The window the recording is anchored to (for "Window" coordinates).
 */
export type WindowInfo = { exe: string, class: string, title: string, rect: Rect, };
