// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Panes } from "./Panes";

export type WindowPrefsView = { expanded: boolean, panes: Panes, };
