// The UI talks to Relay through this interface: the Tauri commands and the
// engine's message stream in the app, or a read-only simulation in a plain
// browser (`npm run dev`).
import { Channel, invoke } from "@tauri-apps/api/core";
import type { EditOp, ExportFormat, MacroListItem, MacroView, PlaybackOptions } from "../types";
import type { EngineMsg } from "./bindings/EngineMsg";
import type { Mode } from "./bindings/Mode";
import type { Settings } from "./bindings/Settings";
import { isTauri } from "../platform/window";

export interface Backend {
  /** False in the browser preview, where macros can't be recorded or edited. */
  readonly editable: boolean;
  /** Receives session updates (mode, countdown, recording progress, playback ticks). */
  subscribe(onMessage: (msg: EngineMsg) => void): Promise<void>;
  toggleRecord(): Promise<void>;
  togglePlay(from: number): Promise<void>;
  stop(): Promise<void>;
  seek(t: number): Promise<void>;
  listMacros(): Promise<MacroListItem[]>;
  loadMacro(id: string): Promise<MacroView>;
  editMacro(id: string, op: EditOp): Promise<MacroView>;
  setPlaybackOptions(id: string, options: PlaybackOptions): Promise<MacroView>;
  exportText(id: string, format: ExportFormat): Promise<string>;
  getSettings(): Promise<Settings>;
  updateSettings(settings: Settings): Promise<Settings>;
}

/** Errors from Rust commands arrive as `{ code, message }`. */
export interface IpcError {
  code: string;
  message: string;
}

const tauriBackend: Backend = {
  editable: true,
  subscribe: async (onMessage) => {
    const channel = new Channel<EngineMsg>();
    channel.onmessage = onMessage;
    await invoke("subscribe_engine", { channel });
  },
  toggleRecord: () => invoke("toggle_record"),
  togglePlay: (from) => invoke("toggle_play", { from }),
  stop: () => invoke("stop_session"),
  seek: (t) => invoke("seek", { t }),
  listMacros: () => invoke("list_macros"),
  loadMacro: (id) => invoke("load_macro", { id }),
  editMacro: (id, op) => invoke("edit_macro", { id, op }),
  setPlaybackOptions: (id, options) => invoke("set_playback_options", { id, options }),
  exportText: (id, format) => invoke("export_text", { id, format }),
  getSettings: () => invoke("get_settings"),
  updateSettings: (settings) => invoke("update_settings", { settings }),
};

interface FixtureItem {
  view: MacroView;
  runs: number;
  last_run_ago_ms: number | null;
  hotkey: string | null;
}

/**
 * The design's sample macros, generated by relay-core's tests, with a small
 * session simulation: the countdown and playback run, recording captures
 * nothing, and step edits need the Rust core.
 */
function browserBackend(): Backend {
  // Loaded lazily so the fixture stays out of the app bundle.
  let items: FixtureItem[] = [];
  const ready = import("../dev/sample-views.json").then((m) => {
    items = structuredClone(m.default as unknown as FixtureItem[]);
  });
  const loadedAt = Date.now();
  let settings: Settings = {
    capture_moves: true,
    capture_keys: true,
    countdown: true,
    ignore_injected: true,
    path_mode: "full",
    show_click_labels: true,
  };
  const find = async (id: string) => {
    await ready;
    const item = items.find((i) => i.view.id === id);
    if (!item) throw { code: "not_found", message: `no macro with id ${id}` } satisfies IpcError;
    return item;
  };
  const unavailable = (): never => {
    throw { code: "unavailable", message: "This needs the Relay app (npm run tauri dev)" } satisfies IpcError;
  };

  // — session simulation —
  let emit: (m: EngineMsg) => void = () => {};
  let mode: EngineMsg & { type: "session" } = { type: "session", mode: "idle", macro_id: null };
  let timer: ReturnType<typeof setInterval> | undefined;
  let play = { t: 0, loop: 0, anchorT: 0, anchorWall: 0, paused: false };
  let current: MacroView | null = null;
  const setMode = (m: Mode) => {
    mode = { ...mode, mode: m };
    emit(mode);
  };
  const halt = () => clearInterval(timer);
  const playTick = () => {
    if (!current) return;
    const pb = current.playback;
    const loops = pb.repeat === "forever" ? null : pb.repeat.count;
    const now = performance.now();
    play.t = play.paused ? play.anchorT : play.anchorT + (now - play.anchorWall) * pb.speed;
    if (play.t >= current.duration) {
      if (loops == null || play.loop + 1 < loops) {
        play = { ...play, loop: play.loop + 1, anchorT: 0, anchorWall: now, t: 0 };
      } else {
        halt();
        emit({ type: "play_tick", t: current.duration, advancing: false, speed: pb.speed, loop_idx: play.loop, loops });
        emit({ type: "finished", reason: "completed" });
        return setMode("idle");
      }
    }
    emit({ type: "play_tick", t: play.t, advancing: !play.paused, speed: pb.speed, loop_idx: play.loop, loops });
  };

  return {
    editable: false,
    subscribe: async (onMessage) => {
      emit = onMessage;
    },
    toggleRecord: async () => {
      halt();
      if (mode.mode === "countdown" || mode.mode === "recording") return setMode("idle");
      if (mode.mode !== "idle") return;
      const start = performance.now();
      if (!settings.countdown) return setMode("recording");
      setMode("countdown");
      timer = setInterval(() => {
        const left = 3000 - (performance.now() - start);
        if (left > 0) return emit({ type: "countdown", left_ms: left });
        halt();
        setMode("recording");
        const recStart = performance.now();
        timer = setInterval(() => {
          const desktop = current?.recording.virtual_desktop ?? { x: 0, y: 0, w: 1920, h: 1080 };
          emit({ type: "rec_progress", elapsed_ms: performance.now() - recStart, desktop, moves: [], steps: null });
        }, 100);
      }, 50);
    },
    togglePlay: async (from) => {
      if (mode.mode === "playing") {
        play = { ...play, anchorT: play.t, paused: true };
        return setMode("paused");
      }
      if (mode.mode === "paused") {
        play = { ...play, anchorWall: performance.now(), paused: false };
        return setMode("playing");
      }
      if (mode.mode !== "idle" || !current) return;
      play = { t: from, loop: 0, anchorT: from >= current.duration - 1 ? 0 : from, anchorWall: performance.now(), paused: false };
      setMode("playing");
      timer = setInterval(playTick, 33);
    },
    stop: async () => {
      halt();
      if (mode.mode === "playing" || mode.mode === "paused") emit({ type: "finished", reason: "stopped" });
      if (mode.mode !== "idle") setMode("idle");
    },
    seek: async (t) => {
      play = { ...play, t, anchorT: t, anchorWall: performance.now() };
    },
    listMacros: async () => {
      await ready;
      return items.map((i) => ({
        id: i.view.id,
        name: i.view.name,
        duration: i.view.duration,
        step_count: i.view.steps.length,
        runs: i.runs,
        last_run: i.last_run_ago_ms == null ? null : new Date(loadedAt - i.last_run_ago_ms).toISOString(),
        hotkey: i.hotkey,
      }));
    },
    loadMacro: async (id) => {
      current = (await find(id)).view;
      mode = { ...mode, macro_id: id };
      return current;
    },
    editMacro: async () => unavailable(),
    setPlaybackOptions: async (id, options) => {
      const item = await find(id);
      item.view = { ...item.view, playback: options };
      if (current?.id === id) {
        // Keep the simulated playhead continuous across speed changes.
        play = { ...play, anchorT: play.t, anchorWall: performance.now() };
        current = item.view;
      }
      return item.view;
    },
    exportText: async (id) => JSON.stringify((await find(id)).view, null, 2),
    getSettings: async () => settings,
    updateSettings: async (s) => (settings = s),
  };
}

export const backend: Backend = isTauri() ? tauriBackend : browserBackend();
