// The UI talks to the macro library through this interface: the Tauri
// commands in the app, or a read-only fixture in a plain browser.
import { invoke } from "@tauri-apps/api/core";
import type { EditOp, ExportFormat, MacroListItem, MacroView, PlaybackOptions } from "../types";
import { isTauri } from "../platform/window";

export interface Backend {
  /** False in the browser preview, where macros can't be edited. */
  readonly editable: boolean;
  listMacros(): Promise<MacroListItem[]>;
  loadMacro(id: string): Promise<MacroView>;
  editMacro(id: string, op: EditOp): Promise<MacroView>;
  setPlaybackOptions(id: string, options: PlaybackOptions): Promise<MacroView>;
  exportText(id: string, format: ExportFormat): Promise<string>;
}

/** Errors from Rust commands arrive as `{ code, message }`. */
export interface IpcError {
  code: string;
  message: string;
}

const tauriBackend: Backend = {
  editable: true,
  listMacros: () => invoke("list_macros"),
  loadMacro: (id) => invoke("load_macro", { id }),
  editMacro: (id, op) => invoke("edit_macro", { id, op }),
  setPlaybackOptions: (id, options) => invoke("set_playback_options", { id, options }),
  exportText: (id, format) => invoke("export_text", { id, format }),
};

interface FixtureItem {
  view: MacroView;
  runs: number;
  last_run_ago_ms: number | null;
  hotkey: string | null;
}

/**
 * The design's sample macros, generated by relay-core's tests. Playback
 * options can change in memory; step edits need the Rust core, so they're
 * only available in the app.
 */
function browserBackend(): Backend {
  // Loaded lazily so the fixture stays out of the app bundle.
  let items: FixtureItem[] = [];
  const ready = import("../dev/sample-views.json").then((m) => {
    items = structuredClone(m.default as unknown as FixtureItem[]);
  });
  const loadedAt = Date.now();
  const find = async (id: string) => {
    await ready;
    const item = items.find((i) => i.view.id === id);
    if (!item) throw { code: "not_found", message: `no macro with id ${id}` } satisfies IpcError;
    return item;
  };
  const readOnly = (): never => {
    throw { code: "unavailable", message: "Editing needs the Relay app (npm run tauri dev)" } satisfies IpcError;
  };
  return {
    editable: false,
    listMacros: async () => {
      await ready;
      return items.map((i) => ({
        id: i.view.id,
        name: i.view.name,
        duration: i.view.duration,
        step_count: i.view.steps.length,
        runs: i.runs,
        last_run: i.last_run_ago_ms == null ? null : new Date(loadedAt - i.last_run_ago_ms).toISOString(),
        hotkey: i.hotkey,
      }));
    },
    loadMacro: async (id) => (await find(id)).view,
    editMacro: async () => readOnly(),
    setPlaybackOptions: async (id, options) => {
      const item = await find(id);
      item.view = { ...item.view, playback: options };
      return item.view;
    },
    exportText: async (id) => JSON.stringify((await find(id)).view, null, 2),
  };
}

export const backend: Backend = isTauri() ? tauriBackend : browserBackend();
