//! Relay core: the macro model, step grouping, edit operations, timeline math,
//! the session state machine, schedules, trigger edge detectors and the `.rly`
//! file format. This crate has no OS or Tauri dependencies.
//!
//! TypeScript bindings for the types the UI sees are generated by ts-rs when
//! the tests run (`cargo test -p relay-core`), into `src/lib/ipc/bindings`.

pub mod edit;
pub mod format;
pub mod keys;
pub mod model;
pub mod schedule;
pub mod session;
pub mod steps;
pub mod timeline;
pub mod triggers;
pub mod view;

#[cfg(any(test, feature = "samples"))]
pub mod samples;

#[cfg(test)]
mod proptests;

pub use edit::{EditError, EditOp};
pub use model::{Event, Macro, Ms};
pub use steps::{Step, StepKind};
pub use view::{MacroListItem, MacroView};
